### ISSUE TITLE
lein doc: java.lang.Long cannot be cast to clojure.lang.Keyword

### ISSUE THREAD

**Issue by fmjrey** [weavejester/codox#91] opened 2015-05-02 18:16 UTC
This happens when running lein doc on https://github.com/fmjrey/combi-tree
```clojure
francois@black:~/Dev/Clojure/combi-tree$ lein clean
francois@black:~/Dev/Clojure/combi-tree$ lein cljx
Rewriting src/cljx to target/generated/src/clj (clj) with features #{clj} and 0 transformations.
Rewriting src/cljx to target/generated/src/cljs (cljs) with features #{cljs} and 1 transformations.
Rewriting test/cljx to target/generated/test/clj (clj) with features #{clj} and 0 transformations.
Rewriting test/cljx to target/generated/test/cljs (cljs) with features #{cljs} and 1 transformations.
francois@black:~/Dev/Clojure/combi-tree$ lein doc
Could not generate clojure documentation for combi-tree.combi-tree - root cause: java.lang.ClassCastException java.lang.Long cannot be cast to clojure.lang.Keyword
Generated HTML docs in /home/francois/Dev/Clojure/combi-tree/doc
```

**Comment by weavejester** [comment] 2015-05-02 21:28
Thanks for the report. It turns out the problem is in the `protocol?` function:

```clojure
(defn- protocol? [var]
  (let [value (var-get var)]
    (and (map? value) (:on-interface value))))
```

A keyword lookup on a sorted map throws an error, instead of returning `nil`:

```clojure
user=> (:foo (sorted-map 0 ()))
ClassCastException java.lang.Long cannot be cast to clojure.lang.Keyword
```

This looks like a longstanding bug in the Clojure compiler ([CLJ-1242](http://dev.clojure.org/jira/browse/CLJ-1242)).

A quick hacky solution is just to explicitly check for sorted maps, e.g.

```clojure
(defn- protocol? [var]
  (let [value (var-get var)]
    (and (map? value) (not (sorted? value)) (:on-interface value))))
```

I'll get this fix out soon. I'd also encourage you to upvote the JIRA issue (if you have a login) so that it gets fixed in Clojure :)

**Comment by fmjrey** [comment] 2015-05-02 21:45
JIRA upvoted, thanks.

**Closed** 2015-05-02 22:07 UTC
Labels: bug

**Comment by weavejester** [comment] 2015-05-02 22:39
This should be fixed in version 0.8.12.

**Comment by fmjrey** [comment] 2015-05-03 06:43
Yes it is, thanks a lot.

**Comment by xiongtx** [comment] 2017-04-28 16:48
This has been addressed in [CLJ-1242](https://dev.clojure.org/jira/browse/CLJ-1242), which is part of Clojure 1.9.
